# Generated by Django 4.1.2 on 2022-10-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('codigo', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('codigo', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('nif', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('codigo_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departamento')),
            ],
        ),
    ]
